// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPgaWtI8zFsSbH8v2RK9MFJ5cSwzl5tLU',
    appId: '1:203532315294:web:168f1fe282601ae672698f',
    messagingSenderId: '203532315294',
    projectId: 'studytime-25219',
    authDomain: 'studytime-25219.firebaseapp.com',
    storageBucket: 'studytime-25219.appspot.com',
    measurementId: 'G-SFZLY59D3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAgLN6Yrmgqi0ZYwo3xd5RxT2CVxw7YEY',
    appId: '1:203532315294:android:8ec572c92f20d99172698f',
    messagingSenderId: '203532315294',
    projectId: 'studytime-25219',
    storageBucket: 'studytime-25219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7O09F2ynYWOxFhcSMZHMraF8iNC-q_iA',
    appId: '1:203532315294:ios:893a49d6d4174da972698f',
    messagingSenderId: '203532315294',
    projectId: 'studytime-25219',
    storageBucket: 'studytime-25219.appspot.com',
    iosBundleId: 'com.example.studytime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7O09F2ynYWOxFhcSMZHMraF8iNC-q_iA',
    appId: '1:203532315294:ios:db3d68a6bb7c949e72698f',
    messagingSenderId: '203532315294',
    projectId: 'studytime-25219',
    storageBucket: 'studytime-25219.appspot.com',
    iosBundleId: 'com.example.studytime.RunnerTests',
  );
}
